server:
  port: 9090

spring:
  application:
    name: service-gateway

  # Serve static files from resources/static/
  webflux:
    static-path-pattern: /**

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: ["*"]
            allowedMethods: [GET, POST, PUT, PATCH, DELETE, OPTIONS]
            allowedHeaders: ["*"]
            allowCredentials: false
            maxAge: 3600

      routes:
        - id: service-voluntarios
          uri: http://localhost:8082
          predicates:
            - Path=/voluntarios/**

        - id: service-donantes
          uri: http://localhost:8082
          predicates:
            - Path=/donantes/**

        - id: service-gestion
          uri: http://localhost:8083
          predicates:
            - Path=/gestion/**

        - id: service-catalogo
          uri: http://localhost:8084
          predicates:
            - Path=/catalogo/**
