-- Schema service-catalogo
CREATE TABLE IF NOT EXISTS articulos_catalogo (
    id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre       VARCHAR(150),
    categoria    VARCHAR(100),
    subcategoria VARCHAR(100),
    rango_edad   VARCHAR(50),
    prioridad    VARCHAR(20),
    meta_stock   INT,
    stock_actual INT DEFAULT 0,
    activo       TINYINT(1) DEFAULT 1,
    descripcion  TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO articulos_catalogo (nombre, categoria, subcategoria, rango_edad, prioridad, meta_stock, stock_actual, descripcion) VALUES

-- ROPA
('Abrigos y chaquetas','Ropa','Abrigos','0-2 años','Alta',40,0,'Abrigos y chaquetas de abrigo para bebés en buen estado.'),
('Abrigos y chaquetas','Ropa','Abrigos','3-6 años','Alta',40,0,'Abrigos y chaquetas de abrigo para niños en buen estado.'),
('Abrigos y chaquetas','Ropa','Abrigos','7-12 años','Alta',40,0,'Abrigos y chaquetas de abrigo para niños mayores.'),
('Abrigos y chaquetas','Ropa','Abrigos','13-17 años','Alta',30,0,'Abrigos y chaquetas para adolescentes.'),
('Poleras y camisetas','Ropa','Poleras','0-2 años','Media',50,0,'Poleras y camisetas en buen estado para bebés.'),
('Poleras y camisetas','Ropa','Poleras','3-6 años','Media',50,0,'Poleras y camisetas en buen estado para niños.'),
('Poleras y camisetas','Ropa','Poleras','7-12 años','Media',50,0,'Poleras y camisetas para niños mayores.'),
('Poleras y camisetas','Ropa','Poleras','13-17 años','Media',40,0,'Poleras y camisetas para adolescentes.'),
('Pantalones y jeans','Ropa','Pantalones','0-2 años','Media',40,0,'Pantalones y jeans en buen estado para bebés.'),
('Pantalones y jeans','Ropa','Pantalones','3-6 años','Media',40,0,'Pantalones y jeans para niños.'),
('Pantalones y jeans','Ropa','Pantalones','7-12 años','Media',40,0,'Pantalones y jeans para niños mayores.'),
('Pantalones y jeans','Ropa','Pantalones','13-17 años','Media',30,0,'Pantalones y jeans para adolescentes.'),
('Pijamas','Ropa','Pijamas','0-2 años','Media',30,0,'Pijamas en buen estado para bebés.'),
('Pijamas','Ropa','Pijamas','3-6 años','Media',30,0,'Pijamas en buen estado para niños.'),
('Pijamas','Ropa','Pijamas','7-12 años','Media',30,0,'Pijamas para niños mayores.'),
('Pijamas','Ropa','Pijamas','13-17 años','Baja',20,0,'Pijamas para adolescentes.'),
('Ropa interior','Ropa','Ropa interior','0-2 años','Alta',60,0,'Ropa interior nueva para bebés.'),
('Ropa interior','Ropa','Ropa interior','3-6 años','Alta',60,0,'Ropa interior nueva para niños.'),
('Ropa interior','Ropa','Ropa interior','7-12 años','Alta',60,0,'Ropa interior nueva para niños mayores.'),
('Ropa interior','Ropa','Ropa interior','13-17 años','Alta',50,0,'Ropa interior nueva para adolescentes.'),

-- CALZADO
('Zapatillas deportivas','Calzado','Zapatillas','0-2 años','Alta',30,0,'Zapatillas deportivas en buen estado para bebés.'),
('Zapatillas deportivas','Calzado','Zapatillas','3-6 años','Alta',30,0,'Zapatillas deportivas para niños.'),
('Zapatillas deportivas','Calzado','Zapatillas','7-12 años','Alta',30,0,'Zapatillas deportivas para niños mayores.'),
('Zapatillas deportivas','Calzado','Zapatillas','13-17 años','Alta',25,0,'Zapatillas deportivas para adolescentes.'),
('Zapatos de colegio','Calzado','Zapatos','3-6 años','Alta',25,0,'Zapatos de colegio en buen estado.'),
('Zapatos de colegio','Calzado','Zapatos','7-12 años','Alta',25,0,'Zapatos de colegio para niños mayores.'),
('Zapatos de colegio','Calzado','Zapatos','13-17 años','Alta',20,0,'Zapatos de colegio para adolescentes.'),
('Botas y botines','Calzado','Botas','0-2 años','Media',20,0,'Botas y botines abrigadores para bebés.'),
('Botas y botines','Calzado','Botas','3-6 años','Media',20,0,'Botas y botines para niños.'),
('Botas y botines','Calzado','Botas','7-12 años','Media',20,0,'Botas y botines para niños mayores.'),
('Botas y botines','Calzado','Botas','13-17 años','Media',15,0,'Botas y botines para adolescentes.'),
('Calcetines','Calzado','Calcetines','0-2 años','Alta',80,0,'Calcetines nuevos para bebés.'),
('Calcetines','Calzado','Calcetines','3-6 años','Alta',80,0,'Calcetines nuevos para niños.'),
('Calcetines','Calzado','Calcetines','7-12 años','Alta',80,0,'Calcetines nuevos para niños mayores.'),
('Calcetines','Calzado','Calcetines','13-17 años','Alta',60,0,'Calcetines nuevos para adolescentes.'),

-- JUGUETES
('Juegos de mesa','Juguetes','Juegos de mesa','3-6 años','Media',20,0,'Juegos de mesa en buen estado para niños pequeños.'),
('Juegos de mesa','Juguetes','Juegos de mesa','7-12 años','Media',20,0,'Juegos de mesa para niños mayores.'),
('Juegos de mesa','Juguetes','Juegos de mesa','13-17 años','Baja',15,0,'Juegos de mesa para adolescentes.'),
('Peluches y muñecos','Juguetes','Peluches','0-2 años','Alta',30,0,'Peluches y muñecos en buen estado para bebés.'),
('Peluches y muñecos','Juguetes','Peluches','3-6 años','Alta',30,0,'Peluches y muñecos para niños.'),
('Rompecabezas','Juguetes','Rompecabezas','3-6 años','Media',25,0,'Rompecabezas educativos para niños.'),
('Rompecabezas','Juguetes','Rompecabezas','7-12 años','Media',25,0,'Rompecabezas para niños mayores.'),
('Juguetes didácticos','Juguetes','Didácticos','0-2 años','Alta',25,0,'Juguetes que estimulan el desarrollo para bebés.'),
('Juguetes didácticos','Juguetes','Didácticos','3-6 años','Alta',25,0,'Juguetes didácticos para niños.'),
('Juguetes de exterior','Juguetes','Exterior','3-6 años','Baja',15,0,'Pelotas, cuerdas y juguetes para el patio.'),
('Juguetes de exterior','Juguetes','Exterior','7-12 años','Baja',15,0,'Juguetes deportivos y de exterior.'),
('Legos y construcción','Juguetes','Construcción','3-6 años','Media',20,0,'Sets de construcción y legos en buen estado.'),
('Legos y construcción','Juguetes','Construcción','7-12 años','Media',20,0,'Legos y construcción para niños mayores.'),

-- ÚTILES ESCOLARES
('Cuadernos','Útiles escolares','Cuadernos','3-6 años','Alta',100,0,'Cuadernos nuevos para párvulos.'),
('Cuadernos','Útiles escolares','Cuadernos','7-12 años','Alta',100,0,'Cuadernos nuevos para escolares.'),
('Cuadernos','Útiles escolares','Cuadernos','13-17 años','Alta',80,0,'Cuadernos nuevos para adolescentes.'),
('Lápices y plumones','Útiles escolares','Lápices','3-6 años','Alta',80,0,'Lápices de colores y plumones para niños.'),
('Lápices y plumones','Útiles escolares','Lápices','7-12 años','Alta',80,0,'Set de lápices y plumones para escolares.'),
('Lápices y plumones','Útiles escolares','Lápices','13-17 años','Alta',60,0,'Lápices de pasta y destacadores para adolescentes.'),
('Mochilas','Útiles escolares','Mochilas','3-6 años','Alta',30,0,'Mochilas en buen estado para párvulos.'),
('Mochilas','Útiles escolares','Mochilas','7-12 años','Alta',30,0,'Mochilas en buen estado para escolares.'),
('Mochilas','Útiles escolares','Mochilas','13-17 años','Alta',25,0,'Mochilas para adolescentes.'),
('Estuches y cartucheras','Útiles escolares','Estuches','3-6 años','Media',40,0,'Estuches y cartucheras para niños.'),
('Estuches y cartucheras','Útiles escolares','Estuches','7-12 años','Media',40,0,'Estuches y cartucheras para escolares.'),
('Tijeras y pegamento','Útiles escolares','Materiales','3-6 años','Media',50,0,'Tijeras de punta roma y pegamento para niños.'),
('Tijeras y pegamento','Útiles escolares','Materiales','7-12 años','Media',50,0,'Materiales de arte y manualidades.'),
('Reglas y escuadras','Útiles escolares','Materiales','7-12 años','Baja',40,0,'Set de geometría para escolares.'),
('Reglas y escuadras','Útiles escolares','Materiales','13-17 años','Media',40,0,'Set de geometría para adolescentes.'),

-- LIBROS
('Cuentos ilustrados','Libros','Cuentos','0-2 años','Media',25,0,'Cuentos con imágenes para bebés y niños pequeños.'),
('Cuentos ilustrados','Libros','Cuentos','3-6 años','Media',25,0,'Cuentos e historias para niños.'),
('Novelas y lecturas','Libros','Novelas','7-12 años','Media',20,0,'Libros de lectura para escolares.'),
('Novelas y lecturas','Libros','Novelas','13-17 años','Media',20,0,'Novelas y libros para adolescentes.'),
('Libros educativos','Libros','Educativos','3-6 años','Media',20,0,'Libros de aprendizaje para preescolar.'),
('Libros educativos','Libros','Educativos','7-12 años','Alta',20,0,'Libros de estudio y apoyo escolar.'),
('Libros educativos','Libros','Educativos','13-17 años','Alta',15,0,'Material de estudio para enseñanza media.'),

-- HIGIENE
('Jabón y shampoo','Higiene','Aseo personal','0-2 años','Alta',60,0,'Jabón y shampoo para bebés (preferir nuevos).'),
('Jabón y shampoo','Higiene','Aseo personal','3-6 años','Alta',60,0,'Productos de aseo para niños.'),
('Jabón y shampoo','Higiene','Aseo personal','7-12 años','Alta',60,0,'Productos de aseo para niños mayores.'),
('Jabón y shampoo','Higiene','Aseo personal','13-17 años','Alta',50,0,'Productos de aseo para adolescentes.'),
('Cepillos y pasta dental','Higiene','Dental','3-6 años','Alta',60,0,'Cepillos de dientes y pasta dental para niños.'),
('Cepillos y pasta dental','Higiene','Dental','7-12 años','Alta',60,0,'Higiene dental para niños mayores.'),
('Cepillos y pasta dental','Higiene','Dental','13-17 años','Alta',50,0,'Higiene dental para adolescentes.'),
('Pañales','Higiene','Pañales','0-2 años','Alta',100,0,'Pañales talla N, P, M, G o XG (preferir nuevos).'),
('Toallas y paños','Higiene','Toallas','0-2 años','Media',30,0,'Toallas y paños de baño para bebés.'),
('Toallas y paños','Higiene','Toallas','3-6 años','Media',30,0,'Toallas de baño para niños.'),
('Desodorantes','Higiene','Desodorantes','13-17 años','Media',40,0,'Desodorantes para adolescentes.');

